# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_servo
    - shoulder_servo
    - elbow_servo
    - wrist_servo
    - wrist_rotate_servo
    - gripper_servo
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - base_servo
    - shoulder_servo
    - elbow_servo
    - wrist_servo
    - wrist_rotate_servo
  gains:
    base_servo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_servo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_servo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_servo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_rotate_servo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointPositionController
  joints:
    gripper_servo
  gains:
    gripper_servo:
      p: 100
      d: 1
      i: 1
      i_clamp: 1