camera1:
    qw: 1
    qx: 0
    qy: 0
    qz: 0
    tx: 0
    ty: 0
    tz: 0
    
camera2:
    qw: 1
    qx: 0
    qy: 0
    qz: 0
    tx: 0
    ty: 0
    tz: 0

camera3:
    qw: 1
    qx: 0
    qy: 0
    qz: 0
    tx: 0
    ty: 0
    tz: 0
