# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
base:
  # MX-28
  ID: 0
  Return_Delay_Time: 0
  Min_Voltage_Limit: 60   # 6.00 [V]
  Max_Voltage_Limit: 160  # 16.00[V]
  CW_Angle_Limit: 0       # 0
  CCW_Angle_Limit: 4095   # 360
  Max_Torque: 1023        # 100%
  LED: 1                  # ON
  Goal_Position: 2048     # Initial goal position

shoulder:
  # MX-28
  ID: 1
  Return_Delay_Time: 0
  Min_Voltage_Limit: 60   # 6.00 [V]
  Max_Voltage_Limit: 160  # 16.00[V]
  CW_Angle_Limit: 0       # 0
  CCW_Angle_Limit: 4095   # 360
  Max_Torque: 1023        # 100%
  LED: 1                  # ON
  Goal_Position: 2048     # Initial goal position

elbow:
  # MX-28
  ID: 2
  Return_Delay_Time: 0
  Min_Voltage_Limit: 60   # 6.00 [V]
  Max_Voltage_Limit: 160  # 16.00[V]
  CW_Angle_Limit: 0       # 0
  CCW_Angle_Limit: 4095   # 360
  Max_Torque: 1023        # 100%
  LED: 1                  # ON
  Goal_Position: 2048     # Initial goal position

wrist:
  # AX-12A
  ID: 3
  Return_Delay_Time: 0
  Min_Voltage_Limit: 60   # 6.00 [V]
  Max_Voltage_Limit: 140  # 14.00[V]
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Max_Torque: 1023
  LED: 1
  Goal_Position: 512      # Initial goal position

wrist_rotate: 
  # AX-12A
  ID: 4
  Return_Delay_Time: 0
  Min_Voltage_Limit: 60   # 6.00 [V]
  Max_Voltage_Limit: 140  # 14.00[V]
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Max_Torque: 1023
  LED: 1
  Goal_Position: 512      # Initial goal position

gripper:
  # AX-12A
  ID: 5
  Return_Delay_Time: 0
  Min_Voltage_Limit: 60   # 6.00 [V]
  Max_Voltage_Limit: 140  # 14.00[V]
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  Max_Torque: 1023
  LED: 1
  Goal_Position: 512      # Initial goal position
