base:
  # MX-28
  ID: 1
  Return_Delay_Time: 0
  Min_Voltage_Limit: 60   # 6.00 [V]
  Max_Voltage_Limit: 160  # 16.00[V]
  CW_Angle_Limit: 0       # 0
  CCW_Angle_Limit: 4095   # 360
  Max_Torque: 1023        # 100%
  LED: 1                  # ON
  Goal_Position: 0        # Initial goal position