# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
base:
  # MX-28
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 3
  Min_Position_Limit: 0
  Max_Position_Limit: 4095
# missing shoulder here...

shoulder_horn:
  ID: 3
  Operating_Mode: 3
  Return_Delay_Time: 0


